### ISSUE TITLE
Tracking issue - Kubeflow v1.5 Docs

### ISSUE THREAD

**Issue by shannonbradshaw** [kubeflow/website#3130]
We'll use this issue to track docs updates for the 1.5 release. WG leads, please create issues and add them here for docs changes required for your components in this release.

For the website itself, this section outlines the versioning process:
https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#version-the-website

- [x] https://github.com/kubeflow/website/issues/3131
- [x] https://github.com/kubeflow/website/pull/3194
- [x] https://github.com/kubeflow/website/pull/3184
- [ ] https://github.com/kubeflow/website/issues/3134
- [x] https://github.com/kubeflow/website/issues/3135
- [x] https://github.com/kubeflow/website/pull/3185
- [x] https://github.com/kubeflow/website/pull/3195
- [x] https://github.com/kubeflow/website/pull/3023
- [x] #3162 
- [ ] #3145 

CC:
@kubeflow/wg-automl-leads
@kubeflow/wg-manifests-leads
@kubeflow/wg-notebooks-leads
@kubeflow/wg-pipeline-leads
@kubeflow/wg-training-leads
@kubeflow/kfserving-owners

**Comment by shannonbradshaw** [comment]
@zijianjoy do we need a 1.5 deployment guide (e.g., https://github.com/kubeflow/website/pull/2957)

**Comment by js-ts** [comment]
@shannonbradshaw please add this https://github.com/kubeflow/website/issues/3130

**Comment by zijianjoy** [comment]
Thank you @shannonbradshaw , this is the GKE deployment guide tracking bug: https://github.com/kubeflow/gcp-blueprints/issues/341

**Comment by shannonbradshaw** [comment]
We've now heard from several working groups regarding docs needs for the 1.5 release. I'm pinging leads again in an effort to get the full picture on docs updates we need to be tracking for the 1.5 release. If you've not already created issues, please at least create stub issues for docs changes required. Please reply here with links to docs issues so that we have the full picture.

@kubeflow/wg-automl-leads
@kubeflow/wg-manifests-leads
@kubeflow/wg-notebooks-leads
@kubeflow/wg-pipeline-leads
@kubeflow/wg-training-leads
@kubeflow/kfserving-owners

**Comment by kimwnasptd** [comment]
Thanks for the issue @shannonbradshaw! 

From Notebooks side this is the effort regarding docs that I have in mind https://github.com/kubeflow/website/issues/3145

**Comment by surajkota** [comment]
Can we add these? https://github.com/kubeflow/website/pull/3146, https://github.com/kubeflow/kubeflow/pull/6339

**Comment by shannonbradshaw** [comment]
Thanks, @surajkota. Added!

**Comment by js-ts** [comment]
https://github.com/kubeflow/website/pull/3162

**Comment by shannonbradshaw** [comment]
One more appeal to working group leads...in what issues are you tracking your 1.5 docs updates?
https://github.com/orgs/kubeflow/teams/wg-automl-leads
https://github.com/orgs/kubeflow/teams/wg-manifests-leads
https://github.com/orgs/kubeflow/teams/wg-notebooks-leads
https://github.com/orgs/kubeflow/teams/wg-pipeline-leads
https://github.com/orgs/kubeflow/teams/wg-training-leads
@kubeflow/kfserving-owners

**Comment by surajkota** [comment]
Created #3023 as an alternative for #3146. We should merge atleast one of them
