### ISSUE TITLE
Set up Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [kubeflow/website#3620]
Hi all, I've been asked to [help in setting up GA4](https://github.com/cncf/toc/issues/1139#issuecomment-1800492802); @zijianjoy wrote https://github.com/cncf/toc/issues/1139#issuecomment-1800183917:

> Sounds good, @nate-double-u Please feel free to comment here for how to move forward integrating with CNCF analytics account. The kubeflow website is located in https://github.com/kubeflow/website

I lead the earlier CNCF effort to [upgrade project websites to GA4](https://github.com/cncf/techdocs/issues/108), so @nate-double-u has asked me to help (he's at KubeCon). I can follow a similar process for Kubeflow if you'd like. I'll outline the steps here.

### Tasks

- [x] Create a GA4 site tag under the **CNCF projects** account.
  New GA4 stream measurement ID: **[`G-Y2KDEK0998`](https://analytics.google.com/analytics/web/?pli=1#/p415099881)**
- [ ] Configure the website to use the new site tag. We have two options here:
  - [ ] (Option A) Configure GA4 site tag through Docsy config - 
    #3627
  - [ ] (Option B) Configure GA4 website ID ([gtag.js]) through [Netlify snippet injection], "Google Analytics 4 - only in production", just before `</head>`:
    ```liquid
    {% if CONTEXT == 'production' %}
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-Y2KDEK0998"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'G-Y2KDEK0998');
    </script>
    {% endif %}
    ```
- [ ] Confirm that the GA4 site tag is receiving events
- [ ] Cleanup: drop config using the old UA ID: https://github.com/kubeflow/website/blob/746e719b69e8e43de6994ae449e48eb2174efc26/config.toml#L81-L83
    #3627

### Pre-migration analytics info for the website

- UA ID `UA-135379910-1` is registered using [gtag.js]
- Hosted on Netlify

### Followup

- #3629

### References

Onboarding tracker issue:

- https://github.com/cncf/toc/issues/1139

I know that there existed an issue for the migration already, but given that UA properties aren't functional anymore, this is "Set up" more than a migration:

- #3402

/cc @caniszczyk @nate-double-u @zijianjoy 

[gtag.js]: https://developers.google.com/analytics/devguides/collection/gtagjs
[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by thesuperzapper** [comment]
@chalin do we also want to migrate the google search console ownership?

Which is currently done via this file: https://github.com/kubeflow/website/blob/master/static/google65401334ad4c38b1.html

**Comment by zijianjoy** [comment]
Thank you @chalin for working on this item! I have approved your PR and feel free to comment here if we need any action to complete the task. (Validation, cleanup, etc.)

**Comment by chalin** [comment]
> @chalin do we also want to migrate the google search console ownership?
> 
> Which is currently done via this file: https://github.com/kubeflow/website/blob/master/static/google65401334ad4c38b1.html

@thesuperzapper - moving this thread to:

- #3638
