### ISSUE TITLE
[Tracker] Fix broken links

### ISSUE THREAD

**Issue by hbelmiro** [kubeflow/website#3814]
- [x] https://github.com/kubeflow/website/issues/3808
  - https://github.com/kubeflow/website/pull/3807
- [x] https://github.com/kubeflow/website/issues/3809
  - https://github.com/kubeflow/website/pull/3830
- [x] https://github.com/kubeflow/website/issues/3810
  - https://github.com/kubeflow/website/pull/3878
- [x] https://github.com/kubeflow/website/issues/3811
  - https://github.com/kubeflow/website/pull/3888
- [x] https://github.com/kubeflow/website/issues/3812
- [x] https://github.com/kubeflow/website/issues/3813
  - https://github.com/kubeflow/website/pull/3888

**Comment by Monokaix** [comment]
Another one: https://github.com/kubeflow/website/pull/3815 : )

**Comment by varodrig** [comment]
I have a draft PR for https://github.com/kubeflow/website/issues/3810. please assign to me. thanks. @hbelmiro

**Comment by varodrig** [comment]
@hbelmiro  it seems all tasks are completed. should we close this issue?
